<a href="https://colab.research.google.com/github/juzology/python-for-data-analysis/blob/main/data-analysis-with-python-zero-to-pandas/assignment-3-pandas-practice/assignment-3-pandas-practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 3 - Pandas Data Analysis Practice

<a target="_blank" href="https://colab.research.google.com/github/JovianHQ/notebooks/blob/main/data-analysis-with-python-zero-to-pandas/assignment-3-pandas-practice/assignment-3-pandas-practice.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

As you go through this notebook, you will find a **???** in certain places. To complete this assignment, you must replace all the **???** with appropriate values, expressions or statements to ensure that the notebook runs properly end-to-end.

Some things to keep in mind:

* Make sure to run all the code cells, otherwise you may get errors like `NameError` for undefined variables.
* Do not change variable names, delete cells or disturb other existing code. It may cause problems during evaluation.
* In some cases, you may need to add some code cells or new statements before or after the line of code containing the **???**.
* Questions marked **(Optional)** will not be considered for evaluation, and can be skipped. They are for your learning.

This tutorial is an executable [Jupyter notebook](https://jupyter.org). Click the **Open in Colab** button at the top of this page to execute the code.

>  **Jupyter Notebooks**: This notebook is made of _cells_. Each cell can contain code written in Python or explanations in plain English. You can execute code cells and view the results instantly within the notebook. Jupyter is a powerful platform for experimentation and analysis. Don't be afraid to mess around with the code & break things - you'll learn a lot by encountering and fixing errors. You can use the "Kernel > Restart & Clear Output" menu option to clear all outputs and start again from the top.

In [2]:
import pandas as pd

In this assignment, we're going to analyze an operate on data from a CSV file. Let's begin by downloading the CSV file.

In [3]:
from urllib.request import urlretrieve

urlretrieve('https://raw.githubusercontent.com/JovianHQ/notebooks/refs/heads/main/data-analysis-with-python-zero-to-pandas/assignment-3-pandas-practice/countries.csv'
            , "countries.csv")

('countries.csv', <http.client.HTTPMessage at 0x79687e616ad0>)

Let's load the data from the CSV file into a Pandas data frame.

In [4]:
countries_df = pd.read_csv('countries.csv')

In [4]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987
1,Albania,Europe,2877800.0,78.57,2.89,11803.431
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839
3,Andorra,Europe,77265.0,83.73,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495
...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775

**Q1: How many countries does the dataframe contain?**

Hint: Use the `.shape` method.

In [5]:
num_countries = countries_df.shape[0]
num_countries

210

In [6]:
print('There are {} countries in the dataset'.format(num_countries))

There are 210 countries in the dataset

**Q2: Retrieve a list of continents from the dataframe?**

*Hint: Use the `.unique` method of a series.*

In [7]:
continents = countries_df['continent'].unique()
continents

array(['Asia', 'Europe', 'Africa', 'North America', 'South America',
       'Oceania'], dtype=object)

In [ ]:
continents

**Q3: What is the total population of all the countries listed in this dataset?**

In [8]:
total_population = countries_df.population.sum()
total_population

np.float64(7757980095.0)

In [15]:
print('The total population is {}.'.format(int(total_population)))

The total population is 7757980095.

**Q: (Optional) What is the overall life expectancy across in the world?**

*Hint: You'll need to take a weighted average of life expectancy using populations as weights.*

In [9]:
weighted_life_expectancy = (countries_df.population * countries_df.life_expectancy).sum() / total_population
weighted_life_expectancy

np.float64(72.72165193409664)

**Q4: Create a dataframe containing 10 countries with the highest population.**

*Hint: Chain the `sort_values` and `head` methods.*

In [20]:
most_populous_df = countries_df.sort_values('population', ascending=False).head(10)[['location']].set_axis(range(1, 11))
most_populous_df

         location
1           China
2           India
3   United States
4       Indonesia
5        Pakistan
6          Brazil
7         Nigeria
8      Bangladesh
9          Russia
10         Mexico

In [21]:
most_populous_df

         location
1           China
2           India
3   United States
4       Indonesia
5        Pakistan
6          Brazil
7         Nigeria
8      Bangladesh
9          Russia
10         Mexico

**Q5: Add a new column in `countries_df` to record the overall GDP per country (product of population & per capita GDP).**

In [24]:
countries_df['gdp'] = countries_df.population * countries_df.gdp_per_capita
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10

In [25]:
countries_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11
...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10

**Q: (Optional) Create a dataframe containing 10 countries with the lowest GDP per capita, among the counties with population greater than 100 million.**

In [30]:
lowest_gdp_by_population = countries_df[countries_df.population > 1e8].sort_values('gdp_per_capita').head(10)[['location']].set_axis(range(1, 11))
lowest_gdp_by_population

       location
1      Ethiopia
2    Bangladesh
3      Pakistan
4       Nigeria
5         India
6   Philippines
7         Egypt
8     Indonesia
9        Brazil
10        China

**Q6: Create a data frame that counts the number countries in each continent?**

*Hint: Use `groupby`, select the `location` column and aggregate using `count`.*

In [31]:
country_counts_df = countries_df.groupby('continent')['location'].count()

In [32]:
country_counts_df

continent
Africa           55
Asia             47
Europe           51
North America    36
Oceania           8
South America    13
Name: location, dtype: int64

**Q7: Create a data frame showing the total population of each continent.**

*Hint: Use `groupby`, select the population column and aggregate using `sum`.*

In [33]:
continent_populations_df = countries_df.groupby('continent')['population'].sum()

In [34]:
continent_populations_df

continent
Africa           1.339424e+09
Asia             4.607388e+09
Europe           7.485062e+08
North America    5.912425e+08
Oceania          4.095832e+07
South America    4.304611e+08
Name: population, dtype: float64

Let's download another CSV file containing overall Covid-19 stats for various countires, and read the data into another Pandas data frame.

In [35]:
urlretrieve('https://raw.githubusercontent.com/JovianHQ/notebooks/refs/heads/main/data-analysis-with-python-zero-to-pandas/assignment-3-pandas-practice/covid-countries-data.csv',
'covid-countries-data.csv')

('covid-countries-data.csv', <http.client.HTTPMessage at 0x796863748d60>)

In [36]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [37]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

**Q8: Count the number of countries for which the `total_tests` data is missing.**

*Hint: Use the `.isna` method.*

In [38]:
total_tests_missing = covid_data_df.total_tests.isna().sum()
total_tests_missing

np.int64(122)

In [39]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

Let's merge the two data frames, and compute some more metrics.

**Q9: Merge `countries_df` with `covid_data_df` on the `location` column.**

*Hint: Use the `.merge` method on `countries_df`.

In [40]:
combined_df = countries_df.merge(covid_data_df, on='location')
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10,38243.0,1409.0,NaN
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10,9728.0,296.0,NaN
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11,45158.0,1525.0,NaN
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN,1199.0,53.0,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11,2729.0,109.0,NaN
...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11,1046.0,35.0,261004.0
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN,766.0,1.0,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10,1976.0,571.0,NaN
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10,12415.0,292.0,NaN
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10,6638.0,206.0,97272.0

In [ ]:
combined_df

**Q10: Add columns `tests_per_million`, `cases_per_million` and `deaths_per_million` into `combined_df`.**

In [41]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [42]:
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [43]:
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [44]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,gdp,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,7.022622e+10,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,3.396791e+10,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,6.101364e+11,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265.0,83.73,NaN,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,1.912651e+11,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,6.007624e+11,1046.0,35.0,261004.0,2681.403324,10.745996,0.359570
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,NaN,766.0,1.0,NaN,NaN,1282.373228,1.674116
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,4.411699e+10,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,6.782303e+10,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,2.823622e+10,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989

**Q11: Create a dataframe with 10 countires that have highest number of tests per million people.**

In [47]:
highest_tests_df = combined_df.sort_values('tests_per_million', ascending=False).head(10)[['location']].set_axis(range(1, 11))
highest_tests_df

                location
1   United Arab Emirates
2                Bahrain
3             Luxembourg
4                  Malta
5                Denmark
6                 Israel
7                Iceland
8                 Russia
9          United States
10             Australia

In [ ]:
highest_tests_df

**Q12: Create a dataframe with 10 countires that have highest number of positive cases per million people.**

In [52]:
highest_cases_df =  combined_df.sort_values('cases_per_million', ascending=False).head(10)[['location']].set_axis(range(1, 11))
highest_cases_df

         location
1           Qatar
2         Bahrain
3          Panama
4           Chile
5      San Marino
6           Aruba
7          Kuwait
8            Peru
9          Brazil
10  United States

In [54]:
highest_cases_df

         location
1           Qatar
2         Bahrain
3          Panama
4           Chile
5      San Marino
6           Aruba
7          Kuwait
8            Peru
9          Brazil
10  United States

**Q13: Create a dataframe with 10 countires that have highest number of deaths cases per million people?**

In [55]:
highest_deaths_df = combined_df.sort_values('deaths_per_million', ascending=False).head(10)[['location']].set_axis(range(1, 11))
highest_deaths_df

          location
1       San Marino
2             Peru
3          Belgium
4          Andorra
5            Spain
6   United Kingdom
7            Chile
8            Italy
9           Brazil
10          Sweden

**(Optional) Q: Count number of countries that feature in both the lists of "highest number of tests per million" and "highest number of cases per million".**

In [59]:
high_count_countries = len(highest_tests_df.merge(highest_cases_df, on='location'))
high_count_countries

2

**(Optional) Q: Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list.**

In [61]:
countries_lowest_gdp_top_20 = combined_df[combined_df.population > 1e7].sort_values('gdp_per_capita').head(20)[['location']].set_axis(range(1, 21))
countries_lowest_gdp_top_20

                        location
1                        Burundi
2   Democratic Republic of Congo
3                          Niger
4                         Malawi
5                     Mozambique
6                     Madagascar
7                          Yemen
8                    South Sudan
9                          Haiti
10                        Uganda
11                  Burkina Faso
12                      Ethiopia
13                          Chad
14                   Afghanistan
15                        Rwanda
16                      Zimbabwe
17                        Guinea
18                          Mali
19                         Benin
20                         Nepal

In [62]:
countries_lowest_hospital_beds_top_20 = combined_df[combined_df.population * 1000 > 1e7].sort_values('hospital_beds_per_thousand').head(20)[['location']].set_axis(range(1, 21))
countries_lowest_hospital_beds_top_20

        location
1           Mali
2     Madagascar
3       Ethiopia
4         Guinea
5          Niger
6          Nepal
7   Burkina Faso
8    Afghanistan
9          Benin
10        Uganda
11         India
12      Pakistan
13     Guatemala
14         Haiti
15       Eritrea
16      Honduras
17         Yemen
18          Togo
19      Tanzania
20    Mozambique

In [66]:
low_count_countries = len(countries_lowest_gdp_top_20.merge(countries_lowest_hospital_beds_top_20,on='location'))
low_count_countries

13

## Submission

Congratulations on making it this far! You've reached the end of this assignment, and you just completed your first real-world data analysis problem.

To save your work, select "File" > "Save a Copy in Drive" on Google Colab. Once the copy is created, click the "Share" button and select "Anyone with the link" under the "General Access" section to make this notebook publicly accessible.

<img src="https://miro.medium.com/v2/resize:fit:800/format:webp/1*4eXpS4TgIJ6n7obsaUKptQ.png" height="400">

Then, copy the notebook link and submit it on the assignment page.